"project_id": "778130"
"base_path": "./src/main/resources/assets/dmr/lang/"
"base_url": "https://api.crowdin.com"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

"preserve_hierarchy": true

files: [
  {
    "source": "en_us.json",
    "translation": "%locale_with_underscore%.json",
    "dest": "lang.json",
  }
]