modLoader = "javafml"
loaderVersion= "${loader_version_range}"
license="${mod_license}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId= "${mod_id}"
displayName="${mod_name}"
version="${mod_version}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
mandatory = true
versionRange="${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange="${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "${geckolib_version_range}"
ordering = "NONE"
side = "CLIENT"