name: Full Deployment

on:
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  game-tests:
    uses: ./.github/workflows/game-tests.yaml
  
  semantic-release:
    needs: game-tests
    uses: ./.github/workflows/semantic-release.yaml
    with:
      dry-run: true
  
  deploy:
    needs: semantic-release
    uses: ./.github/workflows/release.yaml
    if: ${{ needs.semantic-release.outputs.new_release_published }} == 'true' && github.ref == 'refs/heads/main' && github.event_name == 'push' && success()
    with:
      new_release_version: ${{ needs.semantic-release.outputs.new_release_version }}
      changelog: ${{ needs.semantic-release.outputs.changelog }}
  
  set-version-tags:
    needs: deploy
    uses: ./.github/workflows/semantic-release.yaml
    with:
      dry-run: false