name: Full Deployment

on:
  workflow_dispatch:
    inputs:
      new_release_version:
        description: 'The new release version'
        required: true
        type: string
      changelog:
        description: 'The changelog value'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  game-tests:
    uses: ./.github/workflows/game-tests.yaml
  
  deploy:
    needs: game-tests
    uses: ./.github/workflows/release.yaml
    with:
      new_release_version: ${{ github.event.inputs.new_release_version }}
      changelog: ${{ github.event.inputs.changelog }}